// src/components/ShareCard.tsx
// Generates a downloadable PNG prediction card using HTML5 Canvas
import type { PredictResponse } from "../types";
import { getTeamColor } from "../teamColors";

interface Props { result: PredictResponse; venue: string; }

const ShareCard = ({ result, venue }: Props) => {
  const handleShare = () => {
    const W = 800, H = 420;
    const canvas = document.createElement("canvas");
    canvas.width = W * 2;
    canvas.height = H * 2;
    const ctx = canvas.getContext("2d")!;
    ctx.scale(2, 2);

    const c1 = getTeamColor(result.team1);
    const c2 = getTeamColor(result.team2);

    // ── Background ──
    ctx.fillStyle = "#050b1a";
    ctx.fillRect(0, 0, W, H);

    // Subtle gradient overlay
    const grad = ctx.createRadialGradient(W * 0.5, 0, 0, W * 0.5, 0, W * 0.8);
    grad.addColorStop(0, "rgba(59,130,246,0.07)");
    grad.addColorStop(1, "transparent");
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, W, H);

    // ── Border ──
    ctx.strokeStyle = "rgba(99,179,237,0.18)";
    ctx.lineWidth = 1;
    roundRect(ctx, 20, 20, W - 40, H - 40, 16);
    ctx.stroke();

    // ── App branding ──
    ctx.fillStyle = "#f6c90e";
    ctx.font = "bold 15px 'Arial'";
    ctx.textAlign = "left";
    ctx.fillText("🏏 IPL WIN PREDICTOR", 48, 58);

    // ── Venue ──
    ctx.fillStyle = "#64748b";
    ctx.font = "13px Arial";
    ctx.textAlign = "right";
    ctx.fillText(`📍 ${venue.split(",")[0]}`, W - 48, 58);

    // ── Divider ──
    ctx.strokeStyle = "rgba(99,179,237,0.12)";
    ctx.lineWidth = 0.5;
    ctx.beginPath(); ctx.moveTo(48, 72); ctx.lineTo(W - 48, 72); ctx.stroke();

    // ── VS layout ──
    const cx = W / 2;
    const teamY = 130;

    // Team 1 name
    ctx.fillStyle = c1;
    ctx.font = "bold 22px Arial";
    ctx.textAlign = "right";
    wrapText(ctx, result.team1, cx - 40, teamY, 260, 28);

    // VS
    ctx.fillStyle = "#4a5568";
    ctx.font = "bold 20px Arial";
    ctx.textAlign = "center";
    ctx.fillText("VS", cx, teamY + 4);

    // Team 2 name
    ctx.fillStyle = c2;
    ctx.font = "bold 22px Arial";
    ctx.textAlign = "left";
    wrapText(ctx, result.team2, cx + 40, teamY, 260, 28);

    // ── Probability numbers ──
    ctx.fillStyle = c1;
    ctx.font = "bold 48px Arial";
    ctx.textAlign = "right";
    ctx.fillText(`${result.team1_win_prob}%`, cx - 40, teamY + 80);

    ctx.fillStyle = c2;
    ctx.textAlign = "left";
    ctx.fillText(`${result.team2_win_prob}%`, cx + 40, teamY + 80);

    // ── Split bar ──
    const barY = teamY + 100, barH = 14, barX = 48, barW = W - 96;
    const split = (result.team1_win_prob / 100) * barW;
    ctx.beginPath();
    roundRect(ctx, barX, barY, barW, barH, 7);
    ctx.fillStyle = "#0a1628";
    ctx.fill();

    // Team 1 side
    ctx.beginPath();
    roundRect(ctx, barX, barY, split, barH, 7);
    ctx.fillStyle = c1;
    ctx.fill();

    // Team 2 side
    ctx.beginPath();
    roundRect(ctx, barX + split, barY, barW - split, barH, 7);
    ctx.fillStyle = c2;
    ctx.fill();

    // ── Winner banner ──
    const bannerY = barY + 34;
    ctx.fillStyle = "rgba(225,245,238,0.08)";
    roundRect(ctx, 48, bannerY, W - 96, 44, 8);
    ctx.fill();
    ctx.strokeStyle = "rgba(15,110,86,0.4)";
    ctx.lineWidth = 0.5;
    ctx.stroke();

    ctx.fillStyle = "#34d399";
    ctx.font = "500 16px Arial";
    ctx.textAlign = "center";
    ctx.fillText(`🏆  Predicted winner: ${result.predicted_winner}`, cx, bannerY + 27);

    // ── Bottom branding ──
    ctx.fillStyle = "#1e293b";
    ctx.font = "11px Arial";
    ctx.textAlign = "center";
    ctx.fillText("Generated by IPL Win Predictor · localhost:5173", cx, H - 30);

    // ── Download ──
    const a = document.createElement("a");
    a.href = canvas.toDataURL("image/png");
    a.download = `ipl-prediction-${result.team1.split(" ").pop()}-vs-${result.team2.split(" ").pop()}.png`;
    a.click();
  };

  return (
    <button className="share-btn" onClick={handleShare} title="Download as PNG">
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"
        strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/>
        <polyline points="16 6 12 2 8 6"/>
        <line x1="12" y1="2" x2="12" y2="15"/>
      </svg>
      Share prediction
    </button>
  );
};

// Helper: rounded rect path
function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number, y: number, w: number, h: number, r: number
) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

function wrapText(
  ctx: CanvasRenderingContext2D,
  text: string, x: number, y: number, maxWidth: number, lineH: number
) {
  const words = text.split(" ");
  let line = "";
  let lineY = y;
  for (const word of words) {
    const test = line + word + " ";
    if (ctx.measureText(test).width > maxWidth && line) {
      ctx.fillText(line.trim(), x, lineY);
      line = word + " ";
      lineY += lineH;
    } else { line = test; }
  }
  ctx.fillText(line.trim(), x, lineY);
}

export default ShareCard;
